services:
  ai:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${IMAGE_TAG}
    container_name: bizscan-ai-${PROFILE:-dev}
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - QDRANT_HOST=bizscan-qdrant #로컬 : localhost , 배포 : bizscan-qdrant
      - QDRANT_PORT=6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - bizscan-network
    restart: unless-stopped
    depends_on:
      bizscan-qdrant      

  qdrant:
    image: qdrant/qdrant:latest
    container_name: bizscan-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - bizscan-network
    restart: unless-stopped  
    

networks:
  bizscan-network:
    external: true
    name: docker_bizscan-network